apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extracted-logs
  namespace: cs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs
