adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  size: 20Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki:3100
