apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-archive-handler
  namespace: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-archive-handler
  template:
    metadata:
      labels:
        app: log-archive-handler
    spec:
      containers:
      - name: runner
        image: nginx
        command:
        - bash
        - /scripts/downloader_extractor.sh
        volumeMounts:
        - name: extracted-logs
          mountPath: /data
        - name: scripts
          mountPath: /scripts
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootUser
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootPassword
      volumes:
      - name: extracted-logs
        persistentVolumeClaim:
          claimName: extracted-logs
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0777
