apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
        - "-config.file=/etc/promtail/promtail.yaml"
        volumeMounts:
        - name: log-volume
          mountPath: /data
        - name: promtail-config
          mountPath: /etc/promtail/promtail.yaml
          subPath: promtail.yaml
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: extracted-logs
      - name: promtail-config
        configMap:
          name: promtail-config
