apiVersion: apps/v1
kind: Deployment
metadata:
  name: t3sting-zone
  namespace: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t3sting-zone
  template:
    metadata:
      labels:
        app: t3sting-zone
    spec:
      containers:
      - name: runner
        image: python:3.10
        command:
        - sleep
        - infinity
        volumeMounts:
        - name: extracted-logs
          mountPath: /data
        - name: scripts
          mountPath: /scripts
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootUser
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootPassword
        - name: GRAFANA_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-password
        - name: GRAFANA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-user
        - name: GRAFANA_API_KEY
          valueFrom:
            secretKeyRef:
              name: grafana-api-key
              key: grafana-api-key
      volumes:
      - name: extracted-logs
        persistentVolumeClaim:
          claimName: extracted-logs
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0777

